identifier: l2eezavc06r7h531
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: app
homeFolder: C:\Users\Luis\Documents\Personal\Work\Projects\portfolio
distFolder: dist/app
outDir: C:\Users\Luis\Documents\Personal\Work\Projects\portfolio\dist\static
handle404: ''
allowErrorCollect: true
